service: projectnodeless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"  
layers:
  Pdfkit:
    name: Pdfkit
    compatibleRuntimes:
      - nodejs14.x
    description: Required for Pdfkit
    package:
      artifact: layer/pdfkit-layer.zip
custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules:
      forceExclude:
        - pdfkit
    packager: "npm"

  serverless-offline:
    location: .webpack/service

  customDomain:
    basePath: pdfkit
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /upload
          method: GET

  create_adm:
    handler: src/lambdas/CreateAdm.handler
    events:
      - httpApi:
        path: /create/adm
        method: POST
  
  create_voluntary:
    handler: src/lambdas/CreateVoluntary.handler
    events:
      - httpApi:
        path: /create/voluntary
        method: POST
  
  login_adm:
    handler: src/lambdas/LoginAdm.handler
    events:
      - httpApi:
        path: /login
        method: POST

  pdfkit-demo:
    # provisionedConcurrency: 1
    handler: src/pdf/upload.handler
    layers:
      - { Ref: PdfkitLambdaLayer }
    events:
      - http:
          path: demo
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript