service: projectnodeless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x



functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  create_adm:
    handler: src/lambdas/CreateAdm.handler
    events:
      - httpApi:
        path: /create/adm
        method: POST
  
  create_voluntary:
    handler: src/lambdas/CreateVoluntary.handler
    events:
      - httpApi:
        path: /create/voluntary
        method: POST
  
  login_adm:
    handler: src/lambdas/LoginAdm.handler
    events:
      - httpApi:
        path: /login
        method: POST

plugins:
  - serverless-plugin-typescript